config/routes.rb
Rails.application.routes.draw do
#  get 'home/profilepage'
  root 'home#homepage'

  get 'home/logoutpage'


    get '/signup_signin', to: 'home#signup_signin'
    post '/signup_signin', to: 'home#signup_signin'


    get    '/welcome',   to: 'home#homepage'
    get     '/center',   to:  'center#users'
    get    '/about',     to: 'home#about'
    get    '/contact',   to: 'home#contact'
    get    '/logout',    to: 'home#logoutpage'

    get    '/jobs',       to:  'posts#show_jobs'
    post   '/jobs',       to:  'posts#create'
    put   '/jobs',        to:  'posts#editjobs'

    get    '/meals',      to:  'posts#show_meals'
    post   '/meals',      to:  'posts#create'
    put   '/meals',       to:  'posts#edit_meals'

    get    '/shelters',   to:  'posts#show_shelters'
    post   '/shelters',   to:  'posts#create'
    put   '/shelters',    to:  'posts#edit_shelters'

    get    '/supplies',   to:  'posts#show_supplies'
    post   '/supplies',   to:  'posts#create'
    put   '/supplies',    to:  'posts#edit_supplies'
    
    get    '/profile/:id',   to:  'home#profile'
    post   '/profile',   to:  'post#create'


  devise_for :users

  resources :centers

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/center.rb
class Center < ApplicationRecord
  belongs_to :user
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :center
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :centers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 #skip_before_action :authenticate_user!
protect_from_forgery with: :null_session
    skip_before_action :verify_authenticity_token
	#  def respond_modal_with(*args, &blk)
  #   options = args.extract_options!
  #   options[:responder] = ModalResponder
  #   respond_with *args, options, &blk
  # end
    include PostsHelper
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController

  def index
    @center = Center.all
  end

  def create
    
    @c = Center.new(center_params)
    @c.user_id = current_user.id
      if @c.save
        render '/centers/new'
    else
      puts @c.errors.full_messages
      render '/users/center'
    end
end


  def show
    @center = Center.find(params[:id])
  end

  def edit
    @center = current_user
    @center = Center.find(params[:id])
  end

  def update
    @center = Center.find(params[:id])
    @centerupdate = @center.update(update_params)

    redirect_to center_path(@center)
  end

  def destroy
    @center_delete = Center.find(params[:id])
    if @center_delete.delete
      redirect_to "/centers/new"
    end
  end

  private
    def center_params
      params.require(:center).permit(:name, :location, :description)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def signup_signin
        if current_user
          render '/profile'
        end
    end

    def welcome
    end

    def profilepage

    end

    def logoutpage
    end

    def about
    end

  def contact
  end


  def homepage
    @jobs = Post.where(category: "Jobs")
    @last_job = @jobs.last

    @shelters = Post.where(category: "Shelters")
    @last_shelter = @shelters.last

    @supplies = Post.where(category: "Supplies")
    @last_supplies = @supplies.last

    @meals = Post.where(category: "Meals")
    @last_meal = @meals.last

  end


end

app/controllers/modal_controller.rb
class ModalController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.all
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to user_session_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user
    @post = Post.find(params[:format])
  end

  def update
    @post = Post.find(params[:id])
    @postupdate = @post.update(update_params)

    redirect_to post_path(@post)
  end

  def destroy
    @post_delete = Post.find(params[:id])
    @post_delete.delete
    if @post_delete.delete
      redirect_to "/users/home"
    end
  end


  def show_meals
    @posts = Post.where(category: "Meals")
    render 'meals'
  end

  def show_supplies
    @posts = Post.where(category: "Supplies")
    render 'supplies'
  end

  def show_shelters
    @posts = Post.where(category: "Shelters")
    render 'shelters'
  end

  def show_jobs
    @posts = Post.where(category: "Jobs")
    render 'jobs'
  end

private
  def post_params
    params.require(:create).permit(:title, :content, :category, :center_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
    def profile
        
        if !current_user
           redirect_to welcome_path 
        end
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modal_helper.rb
module ModalHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    
    def center_array
        arr = []
        Center.all.each do |center|
           arr.push([ center.name, center.id ])
        end
        return arr
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/centers/index.html.erb
<div id="all_post">
   <h4><% @center.each do |center| %></h4>
     <div id="job_post" class="center_container">
   <table width=100% border="solid" style="overflow-x:auto;">
   
      <tr>
        <td class="center">
       <strong><%= center.name %></strong>
        
    </td>
   

    <td><%= center.location %>

    </td>

    <td>
        <%= center.description %>

          </td>

    <td class="date">
        <%=center.updated_at.strftime("%B %d, %Y") %>
    </td>

        </tr>
        </table>
    <br />
<!--
    <tr>
    <strong><td><%= link_to 'Show', center_path(center) %></td> |
      <td><%= link_to 'Edit', edit_center_path(center) %></td> |
      <td><%= link_to 'Destroy', center_path(center),method: :delete,
              data: { confirm: 'Are you sure?' } %></td></strong>
    </tr>
-->
</div>
    <% end %>

app/views/centers/new.html.erb
<h1>Post Your Center</h1>

<%= form_with scope: :center, url: centers_path, local: true do |form| %>
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :Location %><br>
    <%= form.text_field :location %>
  </p>

  <p>
    <%= form.label :Description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

   <!-- Trigger/Open The Modal -->
<button id="jobsBtn" onclick="post.jobs()" class="button">Jobs</button>

<!-- The Modal -->
<div id="jobsModal" class="modal">

  <!-- Modal content -->
    <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
    <p>Jobs</p>
    <form method="POST" action="/jobs">
    <input type="hidden" name="[create]category" value="Jobs">
    <input type="text" name="[create]title" placeholder="Title">
    <br>
    <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
    <br>
    <input class="jobsubmit" type="submit" value="Submit">
    </form>

</div>
</div>


   <!-- Trigger/Open The Modal -->
<button id="shelterBtn" onclick="post.shelters()" class="button">Shelter</button>

<!-- The Modal -->
<div id="shelterModal" class="modal">

  <!-- Modal content -->
    <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
    <p>Shelter</p>
    <form method="POST" action="/shelters">
    <input type="hidden" name="[create]category" value="Shelters">
    <input type="text" name="[create]title" placeholder="Title">
    <br>
    <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
    <br>
    <input class="blogsubmit" type="submit" value="Submit">
    </form>

</div>
</div>

   <!-- Trigger/Open The Modal -->
<button id="suppliesBtn" onclick="post.supplies()" class="button">Supplies</button>

<!-- The Modal -->
<div id="suppliesModal" class="modal">

  <!-- Modal content -->
    <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
    <p>Supplies</p>
    <form method="POST" action="/supplies">
    <input type="hidden" name="[create]category" value="Supplies">
    <input type="text" name="[create]title" placeholder="Title">
    <br>
    <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
    <br>
    <input class="blogsubmit" type="submit" value="Submit">
    </form>

</div>
</div>
   <!-- Trigger/Open The Modal -->
<button id="mealsBtn" onclick="post.meals()" class="button">Meals</button>

<!-- The Modal -->
<div id="mealsModal" class="modal">

  <!-- Modal content -->
    <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
    <p>Meals</p>
    <form method="POST" action="/meals">
    <input type="hidden" name="[create]category" value="Meals">
    <input type="text" name="[create]title" placeholder="Title">
    <br>
    <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
    <br>
    <input class="blogsubmit" type="submit" value="Submit">
    </form>

</div>
</div>

app/views/centers/show.html.erb
    <p>
        <%= @center.name %>
    </p>

    <p><%= @center.location %>

    </p>

    <p>
        <%= @center.description %>

    </p>

    <p>
        <%=@center.updated_at.strftime("%B %d, %Y") %>
    </p>

    <br>
    <!-- Trigger/Open The Modal -->
 <button id="jobsBtn" onclick="post.jobs()" class="button">Jobs</button>

 <!-- The Modal -->
 <div id="jobsModal" class="modal">

   <!-- Modal content -->
     <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
     <p>Jobs</p>
     <form method="POST" action="/jobs">
     <input type="hidden" name="[create]category" value="Jobs">
     <input type="text" name="[create]title" placeholder="Title">
     <br>
     <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
     <br>
     <input class="jobsubmit" type="submit" value="Submit">
     </form>

 </div>
 </div>


    <!-- Trigger/Open The Modal -->
 <button id="shelterBtn" onclick="post.shelters()" class="button">Shelter</button>

 <!-- The Modal -->
 <div id="shelterModal" class="modal">

   <!-- Modal content -->
     <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
     <p>Shelter</p>
     <form method="POST" action="/shelters">
     <input type="hidden" name="[create]category" value="Shelters">
     <input type="text" name="[create]title" placeholder="Title">
     <br>
     <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
     <br>
     <input class="blogsubmit" type="submit" value="Submit">
     </form>

 </div>
 </div>

    <!-- Trigger/Open The Modal -->
 <button id="suppliesBtn" onclick="post.supplies()" class="button">Supplies</button>

 <!-- The Modal -->
 <div id="suppliesModal" class="modal">

   <!-- Modal content -->
     <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
     <p>Supplies</p>
     <form method="POST" action="/supplies">
     <input type="hidden" name="[create]category" value="Supplies">
     <input type="text" name="[create]title" placeholder="Title">
     <br>
     <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
     <br>
     <input class="blogsubmit" type="submit" value="Submit">
     </form>

 </div>
 </div>
    <!-- Trigger/Open The Modal -->
 <button id="mealsBtn" onclick="post.meals()" class="button">Meals</button>

 <!-- The Modal -->
 <div id="mealsModal" class="modal">

   <!-- Modal content -->
     <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
     <p>Meals</p>
     <form method="POST" action="/meals">
     <input type="hidden" name="[create]category" value="Meals">
     <input type="text" name="[create]title" placeholder="Title">
     <br>
     <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
     <br>
     <input class="blogsubmit" type="submit" value="Submit">
     </form>

 </div>

app/views/home/about.html.erb
<div id="container">
<h1>About Us</h1>

<p>Are you a felon? Unemployed? Underemployed? Below the poverty line? Homeless?</p>
<p>No worries! Life happens, All of us make mistakes. Don't let your past define you.</p>

<br>
<p>Being a felon doesn't make you a bad worker!</p>
<p>Falling below the poverty line doesn't mean you should be abandoned!</p>
<p>And being homeless doesn't mean you should be left in the dark!</p>

<p>Here at SecondStart we provide oppurtunities to those in need. In areas of housing, meals, supplies as well as providing job oppurtunities.</p>
<p>We know that no matter your past mistakes or endeavors, you're human and you deserve the oppurtunity for a normal life.</p>

<h2>Browse our site. Take advantage. And get your SecondStart!</h2>

<h3>Also get access to our free guide for felons to help you get employed again.</h3>

  <div id="guideDiv">
    <h3>THE PAST IS BEHIND YOU</h3>
    <h2>NOW ITS TIME TO GET TO WORK</h2>
    <p>Finding a Job as a Felon Isn't Impossible and We're Here to Help.</p>
    <button id="guideButton"><a href="https://jobsforfelonshub.com/jobs-for-felons-free-guide/">GIVE ME THE GUIDE</a></button>
  </div>
</div>

app/views/home/center.html.erb
<h1>Users Center</h1>

app/views/home/contact.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>



    <div class="row">


        <div class="column left">
            <h1 id="concern">Concerns?</h1>
            <form class="concerns">
                <p id="finalName">Name</p>
                <textarea id="text"></textarea>

                <p id="finalEmail">Email</p>
                <textarea id="text"></textarea>

                <p id="finalMessage">Message</p>
                <textarea id="message"></textarea>
                <br />

                <button id="sumbitButton"><a href="/recieved"></a>SUMBIT</button>
            </form>

        </div>

        <div class="column middle">

            <h1>Contact Us</h1>
            <h1>MEET OUR CREATORS!</h1>
            <p id="img_cont">
                <a href="https://github.com/Scholfieldc84"><img src="/assets/christina.jpg" /></a>
                <a href="https://github.com/ddickson634"><img src="/assets/dolorian.jpg" /></a>
                <a href="https://github.com/Saigal-Maruvathu"><img src="/assets/saigal.jpg" /></a>
                <a href="https://github.com/Campbell1695"><img src="/assets/sharif.jpg" /></a>
            </p>
        </div>

        <div class="column right">
            <h1 id="general">General</h1>

            <p id="number">(732)-663-7878</p>
            <p id="street">2101 Cecil B Moore Ave.</p>
            <p id="cityStateZip">Philadelphia, PA 19129</p>
            <p id="country">United States</p>
        </div>
    </div>
</body>

app/views/home/homepage.html.erb
<h1>Second Start</h1>
<div class="row" id="all_post">

    <div id="post_column" class="column jobs">

        <div id="post" class="jobscontainer">
            <div class="text">
            <h3 class="heading">Newest Job Post</h3>
                <p class="center_name">Posted by:
                    <%= @last_job.center.name %>
                </p>
             <div class="textarea">

                <p>
                    <strong><%= @last_job.title %></strong>
                </p>

                <p>
                    <%= @last_job.content %>
                </p>

                <p class="date">Posted on:
                    <%=@last_job.updated_at.strftime("%B %d, %Y") %>
                </p>
                <br>
                </div>
            </div>


 <div id="post" class= "sheltercontainer">
   <h3>New listings of Shelters</h3>
   <div id="last_shelter" style="background-color:lightblue ">
      <p>Posted by:
          <%= @last_shelter.center.name %>
      </p>

        </div>
    </div>

    <div id="post_column" class="column shelter">
       
        <div id="post" class="sheltercontainer">
            <div class="text">
            <h3 class="heading">Newest Shelter Listing</h3>
                <p class="center_name">Posted by:
                    <%= @last_shelter.center.name %>
                </p>

<div class="textarea">
    
                <p>
                    <strong><%= @last_shelter.title %></strong>
                </p>


                <p>
                    <%= @last_shelter.content %>
                </p>

                <p class="date">Posted on:
                    <%=@last_shelter.updated_at.strftime("%B %d, %Y") %>
                </p>
                <br>
</div>
            </div>
        </div>
    </div>

    <div id="post_column" class="column supplies">
       
        <div id="post" class="suppliescontainer">
            <div class="text">
            <h3 class="heading">Newest Supply Listing</h3>
                <p class="center_name">Posted by:
                    <%= @last_supplies.center.name %>
                </p>
<div class="textarea">
                <p>
                    <strong><%= @last_supplies.title %></strong>
                </p>

                <p>
                    <%= @last_supplies.content %>
                </p>

                <p class="date">Posted on:
                    <%=@last_supplies.updated_at.strftime("%B %d, %Y") %>
                </p>
                <br>
</div>
            </div>
        </div>
    </div>

    <div id="post_column" class="column food">
       
        <div id="post" class="foodcontainer">
            <div class="text">
            <h3 class="heading">Newest Meals Listing</h3>
                <p class="center_name">Posted by:
                    <%= @last_meal.center.name %>
                </p>
                
                <div class="textarea">

                <p>
                    <strong><%= @last_meal.title %></strong>
                </p>

                <p>
                    <%= @last_meal.content %>
                </p>

                <p class="date">Posted on:
                    <%=@last_meal.updated_at.strftime("%B %d, %Y") %>
                </p>
                <br>
                </div>
            </div>

        </div>
    </div>

app/views/home/landingpage.html.erb
<!--
<h1>Home#landingpage</h1>
<h2>Second Start</h2>
<p>Find me in app/views/home/landingpage.html.erb</p>
-->


<h1>User Profile, Needs post submission (CRUD)</h1>

app/views/home/profile.html.erb
<!--
<h1>Home#landingpage</h1>
<h2>Second Start</h2>
<p>Find me in app/views/home/landingpage.html.erb</p>
-->

<% if !current_user.nil? %>
     <li><a href="/profilepage/<%= current_user.id %>" id="nav_button">MY PROFILE</a></li>
     <% end %>
     
<% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% end %>

                <h1>Post Your Center</h1>

                <%= form_with scope: :center, url: centers_path, local: true do |form| %>
                    <p>
                        <%= form.label :Name %><br>
                            <%= form.text_field :name %>
                    </p>

                    <p>
                        <%= form.label :Location %><br>
                            <%= form.text_field :location %>
                    </p>

                    <p>
                        <%= form.label :Description %><br>
                            <%= form.text_area :description %>
                    </p>

                    <p>
                        <%= form.submit %>
                    </p>
                    <% end %>

                        <!-- Trigger/Open The Modal -->
                        <button id="jobsBtn" onclick="post.jobs()" class="button">Jobs</button>

                        <!-- The Modal -->
                        <div id="jobsModal" class="modal">

                            <!-- Modal content -->
                            <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
                            <p>Jobs</p>
                            <form method="POST" action="/jobs">
                                <input type="text" name="[create]title" placeholder="Title">
                                <br>
                                <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
                                <br>
                                <input type="hidden" name="[create]category" value="Jobs" />
                                <%= select_tag "[create]center_id", options_for_select(center_array) %>
                                <br>
                                <input class="jobsubmit" type="submit" value="Submit">
                            </form>

                        </div>
                        </div>


                        <!-- Trigger/Open The Modal -->
                        <button id="shelterBtn" onclick="post.shelters()" class="button">Shelter</button>

                        <!-- The Modal -->
                        <div id="shelterModal" class="modal">

                            <!-- Modal content -->
                            <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
                            <p>Shelter</p>
                            <form method="POST" action="/shelters">
                                <input type="text" name="[create]title" placeholder="Title">
                                <br>
                                <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
                                <br>
                                <input type="hidden" name="[create]category" value="Shelters" />
                                <%= select_tag "[create]center_id", options_for_select(center_array) %>
                                <br>
                                <input class="blogsubmit" type="submit" value="Submit">
                            </form>

                        </div>
                        </div>

                        <!-- Trigger/Open The Modal -->
                        <button id="suppliesBtn" onclick="post.supplies()" class="button">Supplies</button>

                        <!-- The Modal -->
                        <div id="suppliesModal" class="modal">

                            <!-- Modal content -->
                            <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
                            <p>Supplies</p>
                            <form method="POST" action="/supplies">
                                <input type="text" name="[create]title" placeholder="Title">
                                <br>
                                <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
                                <br>
                                <input type="hidden" name="[create]category" value="Supplies" />
                                <%= select_tag "[create]center_id", options_for_select(center_array) %>
                                <br>
                                <input class="blogsubmit" type="submit" value="Submit">
                            </form>

                        </div>
                        </div>
                        <!-- Trigger/Open The Modal -->
                        <button id="mealsBtn" onclick="post.meals()" class="button">Meals</button>

                        <!-- The Modal -->
                        <div id="mealsModal" class="modal">

                            <!-- Modal content -->
                            <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
                            <p>Meals</p>
                            <form method="POST" action="/meals">
                                <input type="hidden" name="[create]category" value="Meals">
                                <input type="text" name="[create]title" placeholder="Title">
                                <br>
                                <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
                                <br>
                                <input type="hidden" name="[create]category" value="Meals" />
                                <%= select_tag "[create]center_id", options_for_select(center_array) %>
                                <br>
                                <input class="blogsubmit" type="submit" value="Submit">
                            </form>

                        </div>
                        </div>

app/views/home/profilepage.html.erb
<!--
<h1>Home#landingpage</h1>
<h2>Second Start</h2>
<p>Find me in app/views/home/landingpage.html.erb</p>
-->


<h1>User Profile, Needs post submission (CRUD)</h1>


<% if user_signed_in? %>

    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% end %>

                <h1>Post Your Center</h1>

                <%= form_with scope: :center, url: centers_path, local: true do |form| %>
                    <p>
                        <%= form.label :Name %><br>
                            <%= form.text_field :name %>
                    </p>

                    <p>
                        <%= form.label :Location %><br>
                            <%= form.text_field :location %>
                    </p>

                    <p>
                        <%= form.label :Description %><br>
                            <%= form.text_area :description %>
                    </p>

                    <p>
                        <%= form.submit %>
                    </p>
                    <% end %>

                        <!-- Trigger/Open The Modal -->
                        <button id="jobsBtn" onclick="post.jobs()" class="button">Jobs</button>

                        <!-- The Modal -->
                        <div id="jobsModal" class="modal">

                            <!-- Modal content -->
                            <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
                            <p>Jobs</p>
                            <form method="POST" action="/create_job">
                                <input type="text" name="[create]title" placeholder="Title">
                                <br>
                                <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
                                <br>
                                <input class="jobsubmit" type="submit" value="Submit">
                            </form>

                        </div>
                        </div>


                        <!-- Trigger/Open The Modal -->
                        <button id="shelterBtn" onclick="post.shelters()" class="button">Shelter</button>

                        <!-- The Modal -->
                        <div id="shelterModal" class="modal">

                            <!-- Modal content -->
                            <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
                            <p>Shelter</p>
                            <form method="POST" action="/create_shelter">
                                <input type="text" name="[create]title" placeholder="Title">
                                <br>
                                <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
                                <br>
                                <input class="blogsubmit" type="submit" value="Submit">
                            </form>

                        </div>
                        </div>

                        <!-- Trigger/Open The Modal -->
                        <button id="suppliesBtn" onclick="post.supplies()" class="button">Supplies</button>

                        <!-- The Modal -->
                        <div id="suppliesModal" class="modal">

                            <!-- Modal content -->
                            <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
                            <p>Supplies</p>
                            <form method="POST" action="/create_supplies">
                                <input type="text" name="[create]title" placeholder="Title">
                                <br>
                                <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
                                <br>
                                <input class="blogsubmit" type="submit" value="Submit">
                            </form>

                        </div>
                        </div>
                        <!-- Trigger/Open The Modal -->
                        <button id="mealsBtn" onclick="post.meals()" class="button">Meals</button>

                        <!-- The Modal -->
                        <div id="mealsModal" class="modal">

                            <!-- Modal content -->
                            <input id="xBtn" type="image" src="/assets/X.png" onclick="post.close()" width="25" height="25">
                            <p>Meals</p>
                            <form method="POST" action="/meals">
                                <input type="hidden" name="[create]category" value="Meals">
                                <input type="text" name="[create]title" placeholder="Title">
                                <br>
                                <textarea class="POST1" type="text" name="[create]content" placeholder="Post Content" maxlength="150"></textarea>
                                <br>
                                <input class="blogsubmit" type="submit" value="Submit">
                            </form>

                        </div>
                        </div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>